version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build: ./server
    environment:
      - MONGO_URI=mongodb://mongo:27017/voucher
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27018"
    volumes:
      - ./data/mongo:/data/db

volumes:
  mongo_data: